### ISSUE TITLE
Windows RS1 and RS3 images missing in manifest

### ISSUE THREAD

**Issue by thaJeztah** [docker-library/hello-world#56] opened 2019-04-17 08:49 UTC
See https://github.com/docker/for-win/issues/2695#issuecomment-483992855

Looks like the image for Windows 2016 ("RS1") is missing; I did a `docker manifest inspect hello-world` and see only RS4 and RS5 is in the list;

```bash
docker manifest inspect hello-world:latest

....

      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1357,
         "digest": "sha256:04efdea6de289ea7f3d9ddbb8317a82bcd0cfefb397a68a42d53af0737fa74b8",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17134.706"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1046,
         "digest": "sha256:057a2292b00553b4ab8e090487aaa8068bf8da87abd563875ffcbfadaf2d03ac",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.437"
         }
```

Only `17134` (RS4) and `17763` (RS5) are present. 

(Referring to the list of versions in https://github.com/Microsoft/hcsshim/blob/bb6b18cdb527145747b43a770efdea50491dd1d5/osversion/windowsbuilds.go#L5-L9)

```go
package osversion

const (

	// RS2 was a client-only release in case you're asking why it's not in the list.
	RS1 = 14393
	RS3 = 16299
	RS4 = 17134
	RS5 = 17763
)
```

**Comment by thaJeztah** [comment] 2019-04-17 08:49
ping @tianon 

/cc @stefanscherer @gaurav1216

**Comment by StefanScherer** [comment] 2019-04-17 08:59
@thaJeztah this is intended https://github.com/docker-library/hello-world/commit/070ec65daf223a355bbb4738357ec4368af4f24a and https://github.com/docker-library/hello-world/commit/88475d7d4cfb43feda2b74a5bfdaf5ff8f964fb1 removed the two deprecated nanoserver image variants.

See also "Twitter helpdesk" https://twitter.com/tianon/status/1115810354708094976 :-)

**Comment by StefanScherer** [comment] 2019-04-17 10:00
Other idea is to provide at least a `mcr.microsoft.com/windows/servercore:ltsc2016` based hello-world for Windows Server 2016. That is a huge base image for that tiny task, but the only remaining one for that OS version. 🤷‍♂️

**Comment by thaJeztah** [comment] 2019-04-17 12:26
Ah, hmm.... that's indeed hello _world_ 🌎 (just as big)

**Comment by quadespresso** [comment] 2019-04-26 18:51
In case there's still interest in updating the manifest:

```
PS C:\Users\Administrator> docker run hello-world:nanoserver-sac2016

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (windows-amd64, nanoserver-sac2016)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run a Windows Server container with:
 PS C:\> docker run -it mcr.microsoft.com/windows/servercore powershell

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

PS C:\Users\Administrator> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.14393.0 Microsoft Windows NT 10.0.14393.0
```

**Comment by tianon** [comment] 2019-09-04 21:13
@thaJeztah @StefanScherer do you think there's enough value in doing so that we should reconsider providing that huge `hello-world` image just for 2016?

(Otherwise I think we can close this as the removal was "by design" 😞)

**Comment by thaJeztah** [comment] 2019-09-05 08:46
I really don't know at this point; yes, I think it's good to have a `hello-world` available for all platforms, but at the same time, I don't know if its worth the time to wait for 10 minutes for that image to pull, only to get "hello from Docker" printed.

OTOH; likely all images you'll be running use the same base-image, so the experience after that would be better.

Why can't we have nice things? 😞

**Comment by thaJeztah** [comment] 2019-09-05 08:47
@ddebroy @taylorb-microsoft care to add your input?

**Comment by StefanScherer** [comment] 2019-09-10 06:06
I think we can close this issue. There is no updated Nanoserver image for 2016. I know it would be nice for beginners to have a simple command that works "everywhere".

The MSFT documentation list two different images for 2019 and 2016 https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server#windows-server-2019

So, there's a solution that can be fixed in documentation.

**Comment by thaJeztah** [comment] 2019-09-10 16:58
Looks like they use a nano server based example for 2016;

```
docker run microsoft/dotnet-samples:dotnetapp-nanoserver-sac2016
```

**Comment by StefanScherer** [comment] 2019-09-10 18:09
Correct. We'll update our docs in a similar way with PR https://github.com/docker/docker.github.io/pull/9421

**Comment by tianon** [comment] 2019-09-10 18:59
Sounds good, thanks! 👍

**Closed by tianon** 2019-09-10 18:59 UTC
